# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5af54639a9e09a9f69f46e947aa2198c0941abbe6b0b74f01670452a48e43ca6e999c032457fcf992639d548a6bf2f941849ab7525a772fbff7b162a1980523

test:
  secret_key_base: 4758ec140f5a70da7e13eeb174bae1a1109e29313b0c40fcd38882be0792e7818e6bc257d792f7ba299554c53d38b69f0fd06f3d0049cf51c2d382361326425a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
